// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EADCA2_Anime.Migrations
{
    [DbContext(typeof(AnimeDbContext))]
    partial class AnimeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EADCA2_Anime.Model.Anime", b =>
                {
                    b.Property<int>("anime_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("anime_id"), 1L, 1);

                    b.Property<int>("duration")
                        .HasColumnType("int");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("genre_id")
                        .HasColumnType("int");

                    b.Property<double>("rating")
                        .HasColumnType("float");

                    b.Property<string>("season")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("studio_id")
                        .HasColumnType("int");

                    b.Property<string>("synopsis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("anime_id");

                    b.HasIndex("genre_id");

                    b.HasIndex("studio_id");

                    b.ToTable("Anime", "public");
                });

            modelBuilder.Entity("EADCA2_Anime.Model.Character", b =>
                {
                    b.Property<int>("character_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("character_id"), 1L, 1);

                    b.Property<int?>("anime_id")
                        .HasColumnType("int");

                    b.Property<string>("image_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("character_id");

                    b.HasIndex("anime_id");

                    b.ToTable("Character", "public");
                });

            modelBuilder.Entity("EADCA2_Anime.Model.Genre", b =>
                {
                    b.Property<int>("genre_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("genre_id"), 1L, 1);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("genre_id");

                    b.ToTable("Genre", "public");
                });

            modelBuilder.Entity("EADCA2_Anime.Model.Staff", b =>
                {
                    b.Property<int>("staff_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("staff_id"), 1L, 1);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("studio_id")
                        .HasColumnType("int");

                    b.HasKey("staff_id");

                    b.HasIndex("studio_id");

                    b.ToTable("Staff", "public");
                });

            modelBuilder.Entity("EADCA2_Anime.Model.Studio", b =>
                {
                    b.Property<int>("studio_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("studio_id"), 1L, 1);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("studio_id");

                    b.ToTable("Studio", "public");
                });

            modelBuilder.Entity("EADCA2_Anime.Model.Anime", b =>
                {
                    b.HasOne("EADCA2_Anime.Model.Genre", "Genre")
                        .WithMany("Anime")
                        .HasForeignKey("genre_id");

                    b.HasOne("EADCA2_Anime.Model.Studio", "Studio")
                        .WithMany("Anime")
                        .HasForeignKey("studio_id");

                    b.Navigation("Genre");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("EADCA2_Anime.Model.Character", b =>
                {
                    b.HasOne("EADCA2_Anime.Model.Anime", "Anime")
                        .WithMany("Character")
                        .HasForeignKey("anime_id");

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("EADCA2_Anime.Model.Staff", b =>
                {
                    b.HasOne("EADCA2_Anime.Model.Studio", "Studio")
                        .WithMany("Staff")
                        .HasForeignKey("studio_id");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("EADCA2_Anime.Model.Anime", b =>
                {
                    b.Navigation("Character");
                });

            modelBuilder.Entity("EADCA2_Anime.Model.Genre", b =>
                {
                    b.Navigation("Anime");
                });

            modelBuilder.Entity("EADCA2_Anime.Model.Studio", b =>
                {
                    b.Navigation("Anime");

                    b.Navigation("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
